### ISSUE TITLE
Android 11 support

### ISSUE THREAD

**Issue by xronin01** [doubleangels/NextDNSManager#124]
Why did you remove support from Android 11?

**Comment by doubleangels** [comment]
Due to features added that only support Android 12+, support for lower versions has been suspended. Sorry for any inconvenience.

Support for lower Android versions might return, however I cannot guarantee this.

**Comment by doubleangels** [comment]
Upon further review, re-adding support for Android 10+ was trivial so I have done that. It should be rolling out shortly.
