### ISSUE TITLE
setting: Change the site language.

### ISSUE THREAD

**Issue by Wjxfi** [doubleangels/NextDNSManager#15]
I was slipped a foreign language😔

info:
https://help.nextdns.io/t/35hlrj6/change-language-on-the-sites

**Comment by doubleangels** [comment]
I don't believe that this is something that can be done with the current implementation of the app, closing for now.

**Comment by doubleangels** [comment]
The app follows the system's default language as of b54bf634cc5f4ea7ce6718673c25064e0cc137c1.
