### ISSUE TITLE
In a dark theme, make the top bar dark, too

### ISSUE THREAD

**Issue by Wjxfi** [doubleangels/NextDNSManager#17]
![6a262c6d-52b1-42be-bc2b-9b38d2161fc2.jpg](https://github.com/doubleangels/NextDNSManager/assets/113500363/21ed0d57-2102-4809-adad-7b9b92fc9f27)

**Comment by doubleangels** [comment]
This is a great idea, I will work on it and update here.

**Comment by doubleangels** [comment]
This has been implemented as of e36e1c4c53a8a0d65d3b68fc8e9cc9695e80bb05 and will be rolling out shortly. Thanks!
