### ISSUE TITLE
the help page is ugly

### ISSUE THREAD

**Issue by Wjxfi** [doubleangels/NextDNSManager#18]
In the normal browser it's beautiful, in that app it's not...
![d0eeeea8-923d-4ea5-98ab-cf2b3daa3a84.jpg](https://github.com/doubleangels/NextDNSManager/assets/113500363/825fb7c4-b3ef-4b15-800c-6977949e05a2)

**Comment by doubleangels** [comment]
Thanks for reporting this! I will take a look and update here.

**Comment by doubleangels** [comment]
This is fixed as of 03fd516485924370d90035a4dd7b85eec2ae0e25 and should be rolling out soon!
