### ISSUE TITLE
impossible to pay with cores

### ISSUE THREAD

**Issue by Wjxfi** [doubleangels/NextDNSManager#19]
Dogecoin core, bitcoin core, etc.

The problem is at the explanation stage

**Comment by doubleangels** [comment]
Thanks for the info, I will investigate and report back!

**Comment by doubleangels** [comment]
There wasn't enough information provided about this issue to reproduce it, feel free to re-open if you are still experiencing issues. Closing for now.

**Comment by doubleangels** [comment]
I have no idea if you're asking for a feature addition or describing a problem. Can you please be more clear about what you're looking for?

**Comment by doubleangels** [comment]
Thanks for the clarification! This was fixed in commit c1ade2a7bd25b98de45217bfb6dfeed30e6ad630 and should be rolling out in the next release.
