### ISSUE TITLE
[Turn On & Turn Off NextDNS from the app]

### ISSUE THREAD

**Issue by Moxville** [doubleangels/NextDNSManager#197]
**Is your feature request related to a problem? Please describe.**
[Direct option to Turn On & Turn Off NextDNS from the app]

**Describe the solution you'd like**
[Since the official NextDNS app is no longer available in the play store and I started using NextDNSManager in Android. Some apps does not work when NextDNS is On. Many times in a day/week I switch off & on NextDNS for certain apps to work. Maybe some blocklist could be the reason that some Apps do not work as intended and I also find it not easy to play with Allowlist as well. On/Off Toggle feature is easy and faster way to get the job done]

**Describe alternatives you've considered**
[None]

**Additional context**
[None]

**Comment by doubleangels** [comment]
Unfortunately, this is not possible due to some limitations in Android.
