### ISSUE TITLE
[App installment error] android 7.0 Nougat

### ISSUE THREAD

**Issue by Brian2po** [doubleangels/NextDNSManager#20]
![Screenshot_20230715_011832](https://github.com/doubleangels/NextDNSManager/assets/82137041/7bf1b68a-9c49-498a-993e-0add1984971c)

Device: vivo y69
OS: android 7.0 funtouch OS

**Comment by doubleangels** [comment]
Unfortunately, the app only supports Android 9+. Sorry about that!
