### ISSUE TITLE
Change the color of the navigation bar

### ISSUE THREAD

**Issue by Gamefire238** [doubleangels/NextDNSManager#21]
Hi, can you change the color of the navigation button bar below to match the top bar of the app, it looks a bit unsightly
![Screenshot_20230726_193920](https://github.com/doubleangels/NextDNSManager/assets/78879425/6aa735bd-9421-4e5a-9756-242a158faedf)

**Comment by doubleangels** [comment]
This was implemented as of f0a1cc4a76fba49e923d21804e08c986c8389b93 and will be pushed out soon! Thanks for the suggestion!
