### ISSUE TITLE
[Bug/Issue] F-Droid can't build

### ISSUE THREAD

**Issue by licaon-kter** [doubleangels/NextDNSManager#210]
ref: https://gitlab.com/fdroid/fdroiddata/-/jobs/6497851832#L240

the trusted maven repos list is here: https://gitlab.com/fdroid/fdroidserver/-/blob/a002e46997b30649d151be73d55df8714b376510/fdroidserver/scanner.py#L456-L475

ref: https://github.com/doubleangels/NextDNSManager/commit/74eb9c7049959a7ea0fc857b7536a6efa3d955b3

It's nice that you use Gecko, but I guess F-Droid would need to build it from source, like it does for Fennec or Mull

/LE: fyi https://gitlab.com/fdroid/fdroiddata/-/commit/4119818650463c4dd910d0b7ae4e0a32e2b5e54c

**Comment by doubleangels** [comment]
Thank you for letting me know.

**Comment by licaon-kter** [comment]
which of those listed maven repos have `org.mozilla.geckoview:geckoview-nightly` ?

**Comment by doubleangels** [comment]
Current version of the app doesn't use geckoview, the inclusion of the breaking repo was an error. Removing it solves this problem for now.

**Comment by doubleangels** [comment]
@licaon-kter Opened a MR on Gitlab for re-enabling auto updates.

**Comment by doubleangels** [comment]
Waiting for the next update is fine. :)
