### ISSUE TITLE
APK at v4.6.2 has wrong packageName (com.example.angel instead of com.doubleangels.nextdnsmanagement)

### ISSUE THREAD

**Issue by IzzySoft** [doubleangels/NextDNSManager#22]
v4.6.2 identifies as `com.example.angel` instead of `com.doubleangels.nextdnsmanagement` the previous versions used. Was that intended? The [`build.gradle`](https://github.com/doubleangels/NextDNSManager/blob/main/app/build.gradle#L7) suggests otherwise, the release notes don't mention it, a search for "com.example.angel" in your repo doesn't yield a single result – and the `com.example.*` prefix is not intended for apps which are distributed. Can you please check – and attach the APK with the correct `packageName`/`applicationId` to the release? Thanks in advance!

**Comment by IzzySoft** [comment]
PS: `versionCode` of that APK is also weird, it's `4` while the previous release had `158`. Plus the size doubled. What's more, it's signed with a different key as well: one with an almost empty DN. Is that really an official release?

```
Signer #1 certificate DN: C=US
Signer #1 certificate SHA-256 digest: c02a49c4607e92a45ab8fc468b12874cd1c5a2c40b68c8c1880b66d0d8e515e5
Signer #1 certificate SHA-1 digest: 931f3112d33e02dced9f074938738aea25bb445d
Signer #1 certificate MD5 digest: f19b7cdaa5811102e787694ace159c57
Signer #1 key algorithm: RSA
```

The proper certificate (from the previous release) reads:

```
Signer #1 certificate DN: CN=Matthew VerLee, O=DoubleAngels, L=Greeley, ST=CO, C=US
Signer #1 certificate SHA-256 digest: ae706ac9942ea5a445b2a51e790137516d4508c67715659c43956f1728bf69f1
Signer #1 certificate SHA-1 digest: 617dcc556f0a280ef575cedeb4ef8d917abb2cae
Signer #1 certificate MD5 digest: df999695dbfa7d7502dd77c2f1089c63
Signer #1 key algorithm: RSA
```

**Comment by doubleangels** [comment]
Thank you so much for notifying me of this! I got my APK's mixed up! This should be fixed now and the correct APK is attached to the most recent release. Can you confirm this resolves the problem on your end? My apologies!

**Comment by IzzySoft** [comment]
Grabbing… Size looks good … signature looks good … fdroidserver accepts it (so certificate matches) … index successfully built: Thanks, all fine now – confirm APK and release fixed! Auto-updates re-enabled.

While on it: Maybe you want to [pick a badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) and link it to [your app in my repo](https://apt.izzysoft.de/packages/com.doubleangels.nextdnsmanagement/), so the big fat Google one doesn't feel that lonely? :smiley: Feel free to close then (whether you pick the badge or not), as the original problem is solved. This current version will show up with the next sync around 6 pm UTC, now that it's fixed.

**Comment by doubleangels** [comment]
As requested, I added your badge and linked to/added information about your repo in the README as of 993c6cc33853a2efc4196899babf687108ed7657. Thank you for your help in getting it added on F-Droid and the notification today!

**Comment by IzzySoft** [comment]
Gladly, and thanks for the quick reaction!

> getting it added on F-Droid

Just to clarify: It's just in [my repo](https://apt.izzysoft.de/fdroid), not on [F-Droid.org](https://f-droid.org/). My repo is quite popular already and many have it added in their client, but it's not the same. I gladly help you getting started with inclusion there if you wish. For started, you can take a look at [Quick path to get your app into F-Droid](https://gitlab.com/-/snippets/1896503#quick-path-to-get-your-app-into-f-droid).
