### ISSUE TITLE
MMS bloqués 

### ISSUE THREAD

**Issue by Jlc-1908** [doubleangels/NextDNSManager#277]
### FAQ's Checked

Yes

### Severity

High

### Android Version

EMUI 14.2.0

### Device Model

Huawei Pura 70 ultra

### App Version

5.2.0

### Describe the Issue

Il est impossible d'envoyer et de recevoir des MMS. 

### Additional Information

Réseau téléphonique en France. ( Orange, Bouygues Télécom.
Je n'arrive pas à entrer le domaine des APN en liste blanche.

**Comment by doubleangels** [comment]
Hi! Why are you unable to whitelist the APN?

**Comment by doubleangels** [comment]
No response so closing ticket for now, feel free to reopen. :)
