### ISSUE TITLE
DARK View

### ISSUE THREAD

**Issue by henosch** [doubleangels/NextDNSManager#286]
### FAQ's Checked

None

### Severity

None

### Android Version

14

### Device Model

Pixel 8 Pro

### App Version

5.2.1

### Describe the Issue

I don't see the X to delete the entry.

### Additional Information

![Screenshot_20240703-155909](https://github.com/doubleangels/NextDNSManager/assets/59366586/e42039d8-694e-4782-b10f-ddbe39038fb1)

**Comment by doubleangels** [comment]
This is fixed with #303.
