### ISSUE TITLE
App screenshot shows NextDNS Configuration ID

### ISSUE THREAD

**Issue by shivangc22** [doubleangels/NextDNSManager#29]
Just a heads up, the app screenshot shown on the main page features a NextDNS configuration ID. If that ID is yours, other users can utilise it and use up your quota (if you're on the free plan).

Apologies if the ID is not yours/it's not active anymore, just wanted to point it out (same thing happened to me once).

**Comment by doubleangels** [comment]
Thanks for pointing it out! But don't worry, that configuration is not used at all and was removed long ago. :)
