### ISSUE TITLE
Add more than 1 account of nextdns [Feature Request] 

### ISSUE THREAD

**Issue by PrivacyOsint2** [doubleangels/NextDNSManager#292]
### Feature Description

Add more than 1 account of nextdns to the app? I am using many free accounts because I hit limits. Possibly adding an option in the settings have 2 more next dns accounts / switch? I use shelter to have a 2nd next dns app, would be easier to have a option to allow more than 1 account.

### What Problem Would This Solve?

Add more than 1 account.

### Example Usage
1st account at router for all devices computer/ laptops / wifi.
2nd Mobile Phones
3rd account to switch to when account get to limits of 1st account or 2nd.

**Comment by doubleangels** [comment]
Unfortunately, as outlined in FAQ's, I am unable to change core functionality of NextDNS.
