### ISSUE TITLE
Dark mode improvement.

### ISSUE THREAD

**Issue by Hell0Earth** [doubleangels/NextDNSManager#293]
### FAQ's Checked

Yes

### Describe the Enhancement

Actual dark mode is good but not perfect. The app dark mode overrides Next DNS theme so Next DNS gets some inconsistencies on the UI, for example server menu still white. The solution: Dark mode will only modify app theme and for next DNS theme the app will change the site theme with the already provided dark theme by next DNS.

### Use Case

To improve user experience and UI.

### Alternatives Considered

none

### Additional Context

none

**Comment by doubleangels** [comment]
This is fixed with #303.
