### ISSUE TITLE
block mod not working [Issue] 

### ISSUE THREAD

**Issue by musmank1** [doubleangels/NextDNSManager#296]
### FAQ's Checked

Yes

### Severity

Critical

### Android Version

13

### Device Model

Redmi Note 13

### App Version

5.2.1

### Describe the Issue

I am using the Pro version (paid 1 year) and if I set the profile's DNS in the router, then any website that was being blocked will not be blocked, and no logs will be created.

**Comment by doubleangels** [comment]
Sounds like your router configuration is not set up correctly, please look at resources for doing so online.
