### ISSUE TITLE
F-Droid Repository

### ISSUE THREAD

**Issue by crypnull** [doubleangels/NextDNSManager#3]
I like many others have a de-googled phone and use F-Droid as my main source for open source apps, this app would be great to see in the F-Droid reposority as I don't see apk builds outside of those provided on the Play Store which I do not have.

**Comment by mtverlee** [comment]
I will release a signed APK for the short term and look into publishing to F-Droid, thank you for the suggestion!

**Comment by mtverlee** [comment]
You should now be able to access a signed APK [here](https://github.com/mtverlee/NextDNSManager/releases/tag/v3.4.10).

**Comment by mtverlee** [comment]
Due to current conflicts with the F-Droid policies for apps and the way the app currently works, this is shelved for the moment as it would take large amounts of refactoring to be viable.

**Comment by Moonstone3010** [comment]
> Due to current conflicts with the F-Droid policies for apps and the way the app currently works...

Can you please be more specific on that?
You can try temporarily with another repo, such as IzzyOnDroid.

**Comment by mtverlee** [comment]
If you wish, you can read more about F-Droid's [inclusion policy](https://f-droid.org/en/docs/Inclusion_Policy/), but essentially the app's current use of Sentry prevents it from being added to F-Droid.

> We cannot build apps using proprietary tracking/analytic dependencies like Crashlytics and Firebase. Please talk to upstream about an untainted build flavor (either using a FLOSS analytics software like ACRA or by removing Non-Free dependencies completely).

It would be possible to implement a solution like ACRA and push to F-Droid in the future but as this is a side project of mine and since APK's are made available for side loading, that's a considerable amount of work that I don't wish to undertake at the moment. If anyone wishes to make a pull request, go for it!

**Comment by doubleangels** [comment]
I am pleased to announce that the app is available on the following F-Droid repo: `https://apt.izzysoft.de/fdroid/repo`

**Comment by doubleangels** [comment]
@crypnull I am pleased to announce that NextDNSManager has been merged into F-Droid and will be built/added in the coming days!

**Comment by IzzySoft** [comment]
Hi @doubleangels – looks like that went fine, congrats! Your app is still listed with my repo, and the signatures do not match (you didn't achieve reproducible builds with F-Droid) – so at this point I'd remove the app from my repo. As my badge is still present on your Readme, that would cause other confusion ("404 page not found"). To avoid that, may I ask you to let me know when you've removed the badge? Thanks!

**Comment by doubleangels** [comment]
Hey @IzzySoft, not sure I understand why you'd want to pull the app, but your repo has been removed from my documentation as requested. :)

**Comment by IzzySoft** [comment]
Thanks! As for background: all lined out in the repo description, see this section: [Do apps get removed from your repo?](https://apt.izzysoft.de/fdroid/index/info#delete). In your case, the relevant paragraph is:

> Another reason for an app getting removed from my repo is if it was added to the „official F-Droid repository“. Removal then mainly is to avoid confusion at the users' end, due to signature mismatch on updates (if they installed an app from the official repo, signed with F-Droid's key, and an update rolls in earlier via my repo – which is usually the case – there'd be a warning displayed if they'd try to apply that update). In some cases an app still stays with my repo; usually it then uses [reproducible builds](https://f-droid.org/en/docs/Reproducible_Builds/) so there'd be no signature mismatch.

I should maybe update that paragraph, though, as the more problematic thing (from F-Droid's point of view) is one might accidentally install it from my repo and then not be able to switch to the checked-and-built-from-source version at F-Droid… Plus add the point my repo is running on personal space (I don't have "sponsored hardware" etc as F-Droid has). My repo is intended to *complement* F-Droid's, so I try to keep overlap low and rather use available space to offer apps missing there.

**Comment by doubleangels** [comment]
Thanks for the info! And thanks for having it as content while it was up, I appreciated working with you and all your help and support :)
