### ISSUE TITLE
All tags and releases are gone

### ISSUE THREAD

**Issue by IzzySoft** [doubleangels/NextDNSManager#30]
My update checker just reported it could not find any release. A quick check reveals that all tags and releases here seem to be gone. That way, I can no longer keep your app updated in my repo (see the IzzyOnDroid badge on your Readme). Can you please return them?

**Comment by doubleangels** [comment]
They will return, I'm in the process of automating my release/build procedures to avoid any human error and that required a rework of how I handle tags and APK releases. For the time being, current APK's can be found in the release folder (also linked in the README).

**Comment by IzzySoft** [comment]
> They will return

Good to know! Please give me a ping here once they are ready again, so I re-enable updates properly.

> APK's can be found in the release folder

Oof. You're aware that this means any (potential) contributor has to clone them (and their history) along? Putting large binaries inside a git repo is not the best idea (especially for those which can be recreated from the code itself). I'm not complaining, just making sure you're aware of it. It's of course your decision (and not for me to make :wink:).

**Comment by doubleangels** [comment]
That too is a temporary measure, I've just temporarily removed APK's from my gitignore so that people who want to sideload can do so while I work on this build process.  When that's completed, releases will resume as normal, APK's will be readded to the gitignore, and everything should be great! :)

**Comment by IzzySoft** [comment]
Except for those APKs remaining in the git history (unless you plan to rewrite that – which again has other implications e.g. for all forks). Again, just saying. Those who want to sideload can still get the (currently) latest APK from my repo – which is a copy from the latest release here while it still was present. Feel free to point there instead (if you agree; of course it's just a suggestion).

**Comment by doubleangels** [comment]
No you're right, that's a great idea. Thanks for the help :)

**Comment by IzzySoft** [comment]
Gladly – and any time :heart_eyes:

**Comment by doubleangels** [comment]
I have finished the automation for creating releases upon pushing to main. From now on, releases will automatically be created (as they were before, only manually) with the current APK for sideloading and for your repo. Sorry for the confusion!

**Comment by IzzySoft** [comment]
Looks good! Just manually triggered an update check, succeeded. Re-enabled daily checks, the new release will show up with the next sync. Thanks!
