### ISSUE TITLE
[Bug/Issue] 

### ISSUE THREAD

**Issue by Sjsshshsyseuh** [doubleangels/NextDNSManager#300]
### FAQ's Checked

Yes

### Severity

None

### Android Version

14

### Device Model

Xiaomi

**Comment by Sjsshshsyseuh** [comment]
Hhhhbb

**Comment by Sjsshshsyseuh** [comment]
Ghuj vy uigi iignn

**Comment by doubleangels** [comment]
This appears to be spam. Closing.
