### ISSUE TITLE
Crash at startup

### ISSUE THREAD

**Issue by Tripticon84** [doubleangels/NextDNSManager#36]
With the lastest update from the play store the app crash at startup.
I don't know if I can give more information than that.

Device : OnePlus 7T
OS : Lineage OS 20

NextDNSManager version that crash (play store): 4.7.13
NextDNSManager from F-Droid that work: 4.7.11

**Comment by SIRSteiner** [comment]
Same here with v4.7.13 from F-Droid

**Comment by doubleangels** [comment]
Hey guys, I fixed an issue this morning that should fix the crashing that you're experiencing. A new version (4.7.14) with that patch is currently rolling out now. The APK is available here in the releases section, the update should be available on Google Play in a few hours, and the F-Droid updates should take a few days.

I'm going to close this issue for now, but please feel free to re-open it if this update doesn't fix the problem for you. Thanks!

**Comment by SIRSteiner** [comment]
Problem still exist with v4.7.14 from GitHub

**Comment by doubleangels** [comment]
> Problem still exist with v4.7.14 from GitHub

Okay, thanks for letting me know, I'll look into it now.

**Comment by doubleangels** [comment]
@SIRSteiner I am looking for this error you are experiencing and are unable to find it. Would you mind whitelisting `*.o244019.sentry.io` and `*.o244019.ingest.sentry.io` in your NextDNS config and then try and re-launch the app? You can remove those domains from the whitelist afterwards if you want.

**Comment by doubleangels** [comment]
I've made a few changes and pushed out 4.7.15. Please let me know if that resolves your problem, preferably trying the new version with those domains whitelisted, if you're able. Thanks for your patience.

**Comment by SIRSteiner** [comment]
At the moment i can only find v4.7.15. With this version it doesn't work with or without those whitelisted domains. Sorry

**Comment by doubleangels** [comment]
No worries! 4.7.16 is rolling out now, give that a try. :) We're gonna figure this out haha.

**Comment by SIRSteiner** [comment]
The latest working version was v4.7.12.
Device: Xiaomi Mi 9t Pro
OS: MIUI Global 12.5.1 (Android 11)

Maybe that helps...

**Comment by SIRSteiner** [comment]
Success with v4.7.16 also without whitelisted domains. Many thanks!

**Comment by doubleangels** [comment]
Happy to help, thanks for your patience. :)
