### ISSUE TITLE
F-Droid can't build

### ISSUE THREAD

**Issue by licaon-kter** [doubleangels/NextDNSManager#37]
ref: https://gitlab.com/fdroid/fdroiddata/-/jobs/5464767797#L1388

/LE: fyi https://gitlab.com/fdroid/fdroiddata/-/commit/26c3969aa0eab85f645dd21543cd0b91cf2d6c36

**Comment by doubleangels** [comment]
Hey @licaon-kter,

This was an issue with the upstream (this repo) and has been fixed, subsequent builds should not have any problems. Thanks!

**Comment by licaon-kter** [comment]
yup, confirmed https://gitlab.com/fdroid/fdroiddata/-/jobs/5474505163/artifacts/file/tmp/com.doubleangels.nextdnsmanagement_187.apk
