### ISSUE TITLE
Detect or remember which configuration to display

### ISSUE THREAD

**Issue by jeffguillaume** [doubleangels/NextDNSManager#4]
Can the app detect, or at least remember the last, configuration to display when launching?

For example: I have a PC configuration and a Mobile configuration. I'd like the Mobile one to be remembered as selected, or detected upon launch. Currently it defaults to the first configuration and shows the error message "This device is using NextDNS with another configuration."

(Feature addition.)

**Comment by mtverlee** [comment]
Due to the way the app currently works, this isn't viable and would take a large amount of refactoring to be possible. It might be possible in the future though, so it's shelved for now.
