### ISSUE TITLE
Make themed icon

### ISSUE THREAD

**Issue by Undisputed00x** [doubleangels/NextDNSManager#42]
Make a themed icon for the app for those that use A13+

**Comment by doubleangels** [comment]
This is added as of version 4.9.0. This should be rolling out shortly. Thanks!

**Comment by Undisputed00x** [comment]
Nice, thank you for that, you could make the icon a little more detailed in the future like e.g make a diagonal cut line in the badge

**Comment by doubleangels** [comment]
As a part of this process I updated the icon to the current NextDNS icon. It was using the old one before (the one with the diagonal). I might change the icon in the future but I think for now I'm going to try and keep it in line with the official icon.
