### ISSUE TITLE
Your device isn't compatible with this version 

### ISSUE THREAD

**Issue by paulverbeke** [doubleangels/NextDNSManager#51]
I just reinstalled my OnePlus 8T to go from official OxygenOS Android 13 bootloader locked to custom ROM PixelExperience Android 13 bootloader unlocked, and now I cannot download this app from the play store.
![Screenshot_20231210-080957_Google Play Store.png](https://github.com/doubleangels/NextDNSManager/assets/6412153/748cdfe6-9545-480b-be8a-3035e212d432)

I installed it from Neo Store (Fdroid) without problem, then the Play Store says "This application is no longer compatible with your device. Please contact the developers for further information."
![Screenshot_20231210-081038_Google Play Store.png](https://github.com/doubleangels/NextDNSManager/assets/6412153/4211ad1f-ec81-4820-b356-d80437c519fb)

**Comment by doubleangels** [comment]
I will look into this, however I'm not sure there's much I can do. All phones/tablets running Android 9+ are enabled for play store downloads, so I will have to do more research as it seems like your bootloader change is the issue. In the meantime, does side loading with an APK work for you?

**Comment by paulverbeke** [comment]
Yes I can sideload without problem. But it's weird that it happened only on this specific app. Not had any problem with my bank or any other app

**Comment by doubleangels** [comment]
I will be rolling out an update shortly, please feel free to check if it works with Google Play for you.

**Comment by doubleangels** [comment]
Marking this closed for now.
