### ISSUE TITLE
Dark mode that follows system default

### ISSUE THREAD

**Issue by paulverbeke** [doubleangels/NextDNSManager#52]
Could be nice if the app dark mode had a 3rd option "follow system default" enabled by default.

Also I noticed this popup is still in white ![Screenshot_20231210-085321_NextDNS Manager~2.png](https://github.com/doubleangels/NextDNSManager/assets/6412153/5769f9e2-ba13-4ab0-b42d-f39f430ec877)

**Comment by doubleangels** [comment]
The colors in the breadcrumb menu have been fixed as of 4.9.0. The automatic dark mode will be added soon!

**Comment by doubleangels** [comment]
The automatic dark mode is added as of 4.10.
