### ISSUE TITLE
Patch notes?

### ISSUE THREAD

**Issue by candroid-man** [doubleangels/NextDNSManager#76]
I keep seeing this app update but I have no idea what was changed or made better or anything. I'd like to know what each update does, so we know what to thank you for!

**Comment by doubleangels** [comment]
Hi! Thanks for your feedback. Currently, the app publishing is done via an automated process, which is why the current release notes are always the same. More detailed patch notes are planned, don't worry. For now though, you can see what is changed via the commits in this repo.

**Comment by doubleangels** [comment]
This is now implemented as of 4.10.1.
