### ISSUE TITLE
4.10 forced the dark mode

### ISSUE THREAD

**Issue by TairikuOokami** [doubleangels/NextDNSManager#93]

**Comment by doubleangels** [comment]
Yes, as of 4.10, dark mode in the app follows the system setting.

**Comment by TairikuOokami** [comment]
I never understood this obcesion with dark mode, I hate it, because I can not see anything, especially letters, I only use in android to save some battery, but it is disabled in all apps.

**Comment by doubleangels** [comment]
That's understandable. I'm sorry for the inconvenience. Manual theme changing will return, but it's implementation was responsible for a bunch of bugs so that has been removed for the time being while it is reworked. I've discussed this, among other things, in #100.

**Comment by bakancs** [comment]
I struck in the 4.8 version, bc. this is the last what is usable for me. I need to set light mode, bc. I don't like dark mode in this app. But my phone is on dark mode, I like to see the phone settings dark, but it's uncomfortable to search for domains in dark. A dark mode - light mode switcher could be great. Can't you restore the switcher?

**Comment by bakancs** [comment]
Please no forced mode! We need a switcher.

**Comment by doubleangels** [comment]
@TairikuOokami @bakancs Don't worry, selection will come in the 5.0.0 release, I am working on the beta now. :)

**Comment by bakancs** [comment]
> @TairikuOokami @bakancs Don't worry, selection will come in the 5.0.0 release, I am working on the beta now. :)

Ohh, thank's God!

**Comment by bakancs** [comment]
But now that I think it through I have absolutely no problem with that 4.8,it's just works perfectly. Updates usually just bring problems. Once an app works good, it's dumb to update it recklessly :D
